sudo: required

language: bash

services:
  - docker

script:
 - docker-compose build tests
 - docker network create connection_api-tests
 - docker-compose run app --rm composer ci

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master