sudo: required

services:
  - docker

env:
  -
  - PHP_VERSION=7.2
  - PHP_VERSION=7.3
  - PHP_VERSION=7.4
  - PHP_VERSION=8.0

script:
 - echo $PHP_VERSION
 - docker-compose build --build-arg PHP_VERSION=$PHP_VERSION release
 - docker tag keboola/manage-api-tests:latest keboola/manage-api-tests:release$PHP_VERSION
 - docker network create connection_api-tests
 - docker-compose run --rm release composer ci
 - docker images

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
      condition: $PHP_VERSION =~ ^$
  - provider: script
    skip_cleanup: true
    script: ./deploy-tag.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^test- AND $PHP_VERSION =~ ^$
