sudo: required

services:
  - docker

env:
  -
  - PHP_VERSION=8.0

script:
 - docker-compose build --build-arg PHP_VERSION=$PHP_VERSION release$PHP_VERSION
 - docker network create connection_api-tests
 - docker-compose run --rm release composer ci

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./deploy-tag.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^test-
