sudo: required

language: bash

services:
  - docker

script:
 - docker-compose build dev
 - docker network create connection_api-tests
 - docker-compose run --rm dev

deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    branch: master