sudo: required

services:
  - docker

script:
 - echo $PHP_VERSION
 - docker-compose build --build-arg PHP_VERSION=$PHP_VERSION release
 - docker tag keboola/manage-api-tests:latest keboola/manage-api-tests:release$PHP_VERSION
 - docker network create connection_api-tests
 - docker-compose run --rm release composer ci
 - docker images

env:
  - PHP_VERSION= # default php 7.1 version from dockerfile

jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
       - provider: script
         skip_cleanup: true
         script: ./deploy-tag.sh
      if: (tag IS present)
