version: '3.4'
services:
  release:
    build: .
    image: keboola/manage-api-tests
    command: composer ci

  dev: &dev-config
    build: .
    volumes:
      - ./:/code
    environment:
      - ENABLE_DEV_TESTS
      - KBC_MANAGE_API_URL=http://192.168.1.213:8800/
      - KBC_MANAGE_API_TOKEN=2-QV2rULahWcXijBNsLdrjKGNml0AIfG4WbEdi8v8A
      - KBC_SUPER_API_TOKEN=4-DYrVXfnpQ3QkqX0uEqpUcHc1TsUas4n6kToLJw8a
      - KBC_TEST_MAINTAINER_ID=1
      - KBC_TEST_ADMIN_EMAIL
      - KBC_TEST_ADMIN_TOKEN=2-QV2rULahWcXijBNsLdrjKGNml0AIfG4WbEdi8v8A
      - KBC_TEST_ADMIN_WITH_MFA_EMAIL
      - KBC_TEST_ADMIN_WITH_MFA_TOKEN
      - TEST_ABS_ACCOUNT_KEY
      - TEST_ABS_REGION
      - TEST_ABS_ACCOUNT_NAME
      - TEST_ABS_CONTAINER_NAME
      - TEST_ABS_ROTATE_ACCOUNT_KEY
      - TEST_S3_ROTATE_KEY
      - TEST_S3_ROTATE_SECRET
      - TEST_S3_FILES_BUCKET
      - TEST_S3_KEY
      - TEST_S3_REGION
      - TEST_S3_SECRET

  dev-xdebug:
    <<: *dev-config
    build: docker/xdebug
    volumes:
      - ./:/code/
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

networks:
  default:
    external:
      name: connection_api-tests
