name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
        include:
          - php-version: "8.1"
            composer-options: "--ignore-platform-reqs"
            experimental: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker-compose build --build-arg PHP_VERSION=${{ matrix.php-version }} release
          docker network create connection_api-tests
          docker-compose run --rm release php -v
          docker-compose run --rm release composer ci
      - name: List images
        run: docker images
