name: Build on tag

on:
  push:
    tags:
      - test-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker-compose build release
          docker network create connection_api-tests
          docker-compose run --rm release php -v
          docker-compose run --rm release composer ci
      - name: List images
        run: docker images
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Tag and push to quay.io
        run: |
          TAG="${GITHUB_REF##*/}"
          docker tag keboola/manage-api-tests:latest quay.io/keboola/manage-api-tests:$TAG
          docker push quay.io/keboola/manage-api-tests:$TAG
